### ISSUE TITLE
dc.FhirClient.cls - invalid command during container build

### ISSUE THREAD

**Issue by dkutac** [mwaseem75/iris-fhir-client#1]
[iris-fhir-client]      Compile START
Compilation started on 06/03/2022 07:29:41 with qualifiers 'd-lck'
Compiling 2 classes
Compiling class dc.FhirClient
Compiling class dc.FhirServer
Compiling table dc.FhirServer
Compiling routine dc.FhirClient.1
ERROR: dc.FhirClient.cls(Init+33) #1026: Invalid command : '"Error while creating server ID2"' : Offset:9 [zInit+30^dc.FhirClient.1]
 TEXT:                  Quit  "Error while creating server ID2"
Compiling routine dc.FhirServer.1
Detected 1 errors during compilation in 0.194s.

[iris-fhir-client]      Compile FAILURE
ERROR! Error compiling routine: dc.FhirClient.1.  Errors:  ERROR: dc.FhirClient.cls(Init+33) #1026: Invalid command : '"Error while creating server ID2"' : Offset:9The command '/bin/sh -c iris start IRIS     && iris session IRIS < iris.script     && iris stop IRIS quietly' returned a non-zero code: 1
ERROR: Service 'iris' failed to build : Build failed

**Comment by mwaseem75** [comment]
Issue is resolved. Thanks
