### ISSUE TITLE
IPM module is not working

### ISSUE THREAD

**Issue by evshvarov** [mwaseem75/iris-fhir-client#5]
Tells that modules are not installed:
HEALTHTOOLKIT>do ##class(dc.FhirClient).ListResources()

   Set irisfhirclient = ##class(%SYS.Python).Import("irisfhirclient")
   ^
<THROW>ListResources+7^dc.FhirClient.1 *%Exception.PythonException  230 ListResources+7^dc.FhirClient.1^3^        Set irisfhirclient = ##class(%SYS.Python).Import("irisfhirclient") <class 'ModuleNotFoundError'>: No module named 'aiohttp' - Import
HEALTHTOOLKIT 2d1>q

and 
HEALTHTOOLKIT>set count = ##class(dc.FhirClient).CountResource("Patient")
Error While importing irisfhirclient.py file

If you could please add requirements.txt, like [here](https://github.com/intersystems-community/iris-embedded-python-template/blob/master/requirements.txt) - this will make IPM to package python modules listed there to IPM module and install it into IRIS system.

**Comment by mwaseem75** [comment]
Hi @evshvarov
requirements.txt has been added as suggested. 
Thanks

**Comment by evshvarov** [comment]
thank you @mwaseem75 ! Could you please also issue a release on [Open Exchange](https://openexchange.intersystems.com) to republish the IPM module? thank you in advance!

**Comment by mwaseem75** [comment]
@evshvarov, done as suggested.
Thanks

**Comment by evshvarov** [comment]
thank you @mwaseem75! BTW, hope you know that to release a new version on
OEX no approval chain needed - can just issue release directly on OEX.
Thanks a lot!
