### ISSUE TITLE
Wasn't able to use via IPM

### ISSUE THREAD

**Issue by evshvarov** [mwaseem75/iris-fhir-client#9]
I set up a local FHIR server via FHIR tempate.

Having my FHIR server in FHIRSERVER namespace with URL:
http://localhost:32783/fhir/r4/
installed a server as:
do ##class(dc.FhirClient).RegisterServer("Local FHIR Server","http://localhost:32783/fhir/r4/"," "," ")

But UI is not working:

<img width="1287" alt="Screenshot 2024-11-03 at 3 08 40 PM" src="https://github.com/user-attachments/assets/e19d5f98-6215-4fed-b676-bd8ded1266bd">

**Comment by evshvarov** [comment]
CLI is not working either:
```cmd
FHIRSERVER>do ##class(dc.FhirClient).RegisterServer("Local FHIR Server","http://localhost:32783do ##class(dc.FhirClient).RegisterServer("Local FHIR Server","http://localhost:32783/fhir/r4/",do ##class(dc.FhirClient).ListResources()

   do irisfhirclient.ListResources(obj.Endpoint,obj.ApiKey,opt) 
   ^
 }
 //Active Server data is not defined
<THROW>ListResources+8^dc.FhirClient.1 *%Exception.PythonException <PYTHON EXCEPTION> 246 <class 'requests.exceptions.InvalidHeader'>: Invalid leading whitespace, reserved character(s), or return character(s) in header value: ' '
FHIRSERVER 2d1>
```

**Comment by mwaseem75** [comment]
The issue is resolved.
The new release is updated. Please reinstall the application and try.
Thanks
